
GET http://localhost:8888/ebook/list
###

POST http://localhost:8888/ebook/save
Content-Type: application/json

{
  "id": 1
}

###
GET http://localhost:8888/doc/all/1

###
GET http://localhost:8888/user/list?page=1&size=5

###
GET http://localhost:8888/ebook/list?page=1&size=5