GET http://localhost:8888/test

###

POST http://localhost:8888/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###
PUT http://localhost:8888/hello
Content-Type: application/json

{
  "name":"post"
}

###

GET http://localhost:8888/list

###

GET http://localhost:8888/redis/set/123/test
Accept: application/json

###
GET http://localhost:8888/redis/get/320411241305088
Accept: application/json

###
GET http://localhost:8888/ebook-snapshot/get-statistic
Accept: application/json

###
GET http://localhost:8888/ebook-snapshot/get-30-statistic
Accept: application/json

